sudo: required

# whitelist
branches:
  only:
    - master

env:
  - VERSION=2.6.0

before_install:
- wget https://github.com/singularityware/singularity/releases/download/$VERSION/singularity-$VERSION.tar.gz
- tar xvf singularity-$VERSION.tar.gz
- cd singularity-$VERSION
- ./configure --prefix=/usr/local
- make
- sudo make install

script:
  - bash ./script.sh
