sudo: required

# whitelist
branches:
  only:
    - master

before_install:
- git clone https://github.com/singularityware/singularity.git
- cd singularity
- ./autogen.sh
- ./configure --prefix=/usr/local
- make
- make install

script:
  - bash ./script.sh
